apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tp6hy07ft-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tp6hy07ft-java-quarkus-gitops